### ISSUE TITLE
More prominent "Stop screen share" button

### ISSUE THREAD

**Issue by dmke** [livekit/components-js#776]
### Describe the problem

Maybe I'm getting old, but whenever I try to stop sharing my screen, I'm tempted to hit the big red "Leave" button instead:

![image](https://github.com/livekit/components-js/assets/327411/f62b4bff-af9b-4091-8141-c84b977310f6)

(This has actually happened more than a few times now).

As a Firefox user, I occasionally hit its UI control for this:

![image](https://github.com/livekit/components-js/assets/327411/a1121252-e934-49ca-9eba-d3e85fa7e392)

However that thing is (a) relatively small, and (b) seems to pop up on a random monitor (I'm using multiple).

### Describe the proposed solution

Maybe add a little color to the "Stop screen share" button (`background-color: var(--lk-accent-bg)`):

![image](https://github.com/livekit/components-js/assets/327411/2d2ccb69-4d22-4eef-b841-30ead60fcdde)

and/or dim the "Leave" button while screen sharing is active:

![image](https://github.com/livekit/components-js/assets/327411/040d0456-70c0-43de-84cb-a488b4f33a4d)

### Alternatives considered

It would be nice to have a dedicated CSS variable for the button, as this is the minimal CSS selector needed to change the styling:

```css
/* apply accent color (blue) to screen share button, when screen sharing is active */
[data-lk-theme] .lk-button[data-lk-source="screen_share"][data-lk-enabled="true"]:not(:disabled) {
  background-color: var(--lk-accent-bg)
}
```

And even with a dedicated CSS variable, dimming the "Leave" button needs a bit more creativity:

```css
/* dim leave button, when screen sharing is active; should work even if chat is disabled */
[data-lk-theme] .lk-button[data-lk-source="screen_share"][data-lk-enabled="true"]:not(:disabled) + .lk-chat-toggle + .lk-disconnect-button, 
[data-lk-theme] .lk-button[data-lk-source="screen_share"][data-lk-enabled="true"]:not(:disabled)                   + .lk-disconnect-button {
  --lk-control-bg: var(--lk-control-active-bg);
}
```

### Importance

nice to have
